### ISSUE TITLE
Where to get prior information of Starting cell for Margaret?

### ISSUE THREAD

**Issue by Rohit-Satyam** [Zafar-Lab/Margaret#38]
I observed that Margaret uses `Palantir_pseudotime` information and requires user to have prior knowledge of starting cell. Is there an inbuilt function to identify which cells could be used as starting cells or we have to run some other tools to find that out? I think choosing any cell arbitrarily as starting point will be wrong!!

**Comment by kpandey008** [comment]
The starting cell needs to be specified as an input for Margaret. It is possible to identify the starting cells usually using some exploratory analysis like clustering (and then projecting expressions of known marker genes in start cells on the 2d-embedding visualization) or from prior biological knowledge about the dataset you are working with. Choosing an arbitrary starting cell will likely result in incorrect pseudotime and trajectory analysis
